Implemented StatisticService; implemented QuizQuestionFactory.
rimaris/MovieQuiz-ios pull request #3
Opened 2022-12-08 20:53 UTC by rimaris

2022-12-09 16:57 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    public func showAlert(model: AlertModel) {
паблик лишнее, как мне кажется, давай уберем

2022-12-09 17:06 UTC, ABashkirova requested changes
Комментарий на платформе

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        guard let viewController = viewController else {return}
```suggestion
        guard let viewController = viewController else { return }
```

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let formattedDate = dateFormatter.string(from: statisticService.bestGame.date)
в папке Helpers уже создан форматтер для отображения даты, давай воспользуемся функцией из расширения? Не забудь поправить формат

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers) / 10\nКоличество сыгранных квизов: \(statisticService.gamesCount)\nРекорд: \(statisticService.bestGame.correct)/\(statisticService.bestGame.to
Можно использовать [многострочный вариант строки](https://www.swiftbysundell.com/tips/multiline-string-literal-tips-and-tricks/), чтобы строчка кода умещалась в столбец 120-180 символов:

```
let textDog = """
╥━━━━━━━━╭━━╮━━┳
╢╭╮╭━━━━━┫┃▋▋━▅┣
╢┃╰┫┈┈┈┈┈┃┃┈┈╰┫┣
╢╰━┫┈┈┈┈┈╰╯╰┳━╯┣
╢┊┊┃┏┳┳━━┓┏┳┫┊┊┣
╨━━┗┛┗┛━━┗┛┗┛━━┻
"""
```

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    func didRecieveNextQuestion(question: QuizQuestion?) {
Рекоменду [настроить проверку правописания](https://sarunw.com/posts/spell-checking-in-xcode/#how-to-enable-spell-checking-in-xcode), чтобы не выпускать опечатки в продакшен

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/StatisticService.swift
> +
между отдельными смысловыми блоками принято оставлять одну строку
```suggestion
    }
    
    private var correct: Int {
        get {
            return userDefaults.integer(forKey: Keys.correct.rawValue)
        }
        set {
            userDefaults.set(newValue, forKey: Keys.correct.rawValue)
        }
    }
    
    private var total: Int {
        get {
            return userDefaults.integer(forKey: Keys.total.rawValue)
        }
        set {
            return userDefaults.set(newValue, forKey: Keys.total.rawValue)
        }
    }
}
```

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/QuestionFactory.swift
> +        QuizQuestion(image: "The Godfather", text: "Рейтинг этого фильма больше чем 6", correctAnswer: true),
где-то есть `?`, а где-то нет :) давай проверим?

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/QuestionFactoryProtocol.swift
> +    var delegate: QuestionFactoryDelegate? { get set }
а давай из протокола это свойство удалим. Обычно так не делают.

А чтобы инициализировать делегат, можно написать вот так во viewDidLoad
```swift 
let factory = QuestionFactory()
factory.delegate = self
self.questionFactory = factory
```

В целом, если объяснишь почему так сделала – то предложение опциональное

2022-12-09 17:06 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +           show(quiz: viewModel)
Обращу внимание, что пользователь может случайно прожать два раза кнопку ответа или даже много и быстро понажимать на кнопки. 
Это может привести к неверному увеличению счетчика, или лишнего вызова алерта с результатом. 
Принято такое поведение блокировать на время выполнения операции запроса следующего вопроса.
Предлагаю подумать как такое реализовать

2022-12-10 12:45 UTC, rimaris commented on MovieQuiz/QuestionFactoryProtocol.swift
> +    var delegate: QuestionFactoryDelegate? { get set }
Тогда нам придется делать  свойство self.questionFactory опциональным, разве нет?

2022-12-10 13:55 UTC, rimaris commented on MovieQuiz/QuestionFactoryProtocol.swift
> +    var delegate: QuestionFactoryDelegate? { get set }
Тогда нам придется делать  свойство self.questionFactory опциональным, разве нет?

2022-12-10 19:36 UTC, ABashkirova commented on MovieQuiz/QuestionFactoryProtocol.swift
> +    var delegate: QuestionFactoryDelegate? { get set }
> Тогда нам придется делать свойство self.questionFactory опциональным, разве нет?

В этом проекте да. В случае если ты гарантируешь инициализацию, ты можешь использовать Implicity unwraping (!) при объявлении типа. 

Однако если этот код вызывать не во viewDidLoad, а при инициализации viewController'а, тогда это будет необязательно. Этот вариант не актуален для работы с проектом на сториборде, но возможен в прокшене: например специальная фабрика вью контроллера, настраивает зависимости и инджектит их в инициализатор.

2022-12-12 13:03 UTC, merged